// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/notsogenius-netizen/go-notes/api-gateway/proto/gen"
)

type Mutation struct {
}

type NoteChangeEvent struct {
	Operation string    `json:"operation"`
	Note      *gen.Note `json:"note"`
}

type Query struct {
}

type Subscription struct {
}
