// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateNoteInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	UserID  string `json:"userId"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type UpdateNoteInput struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	UserID  string `json:"userId"`
}
