package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"

	"github.com/notsogenius-netizen/go-notes/api-gateway/graph/model"
	"github.com/notsogenius-netizen/go-notes/api-gateway/proto/gen"
)

// CreateNote is the resolver for the createNote field.
func (r *mutationResolver) CreateNote(ctx context.Context, userID string, title string, content string) (*gen.Note, error) {
	note, err := r.NotesClient.CreateNote(ctx, userID, title, content)
	if err != nil {
		return nil, err
	}
	
	// Convert to GraphQL note
	
	return note, nil
}

// UpdateNote is the resolver for the updateNote field.
func (r *mutationResolver) UpdateNote(ctx context.Context, id string, title *string, content *string) (*gen.Note, error) {
	panic(fmt.Errorf("not implemented: UpdateNote - updateNote"))
}

// DeleteNote is the resolver for the deleteNote field.
func (r *mutationResolver) DeleteNote(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteNote - deleteNote"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *noteResolver) CreatedAt(ctx context.Context, obj *gen.Note) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *noteResolver) UpdatedAt(ctx context.Context, obj *gen.Note) (string, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// Note is the resolver for the note field.
func (r *queryResolver) Note(ctx context.Context, id string) (*gen.Note, error) {
	panic(fmt.Errorf("not implemented: Note - note"))
}

// Notes is the resolver for the notes field.
func (r *queryResolver) Notes(ctx context.Context, userID string) ([]*gen.Note, error) {
	panic(fmt.Errorf("not implemented: Notes - notes"))
}

// NoteChanged is the resolver for the noteChanged field.
func (r *subscriptionResolver) NoteChanged(ctx context.Context, userID string) (<-chan *model.NoteChangeEvent, error) {
	panic(fmt.Errorf("not implemented: NoteChanged - noteChanged"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Note returns NoteResolver implementation.
func (r *Resolver) Note() NoteResolver { return &noteResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type noteResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
