package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"

	"github.com/notsogenius-netizen/go-notes/api-gateway/graph/model"
	"github.com/notsogenius-netizen/go-notes/api-gateway/proto/gen"
)

// CreateNote is the resolver for the createNote field.
func (r *mutationResolver) CreateNote(ctx context.Context, input model.CreateNoteInput) (*model.Note, error) {
	note, err := r.NotesClient.CreateNote(ctx, input.UserID, input.Title, input.Content)
	if err != nil {
		return nil, fmt.Errorf("failed to create note: %w", err)
	}

	// Convert to GraphQL note

	return &model.Note{
        ID:        note.Id,
        Title:     note.Title,
        Content:   note.Content,
        UserID:    note.UserId,
        CreatedAt: note.CreatedAt.AsTime(),
        UpdatedAt: note.UpdatedAt.AsTime(),
    }, nil
}

// UpdateNote is the resolver for the updateNote field.
func (r *mutationResolver) UpdateNote(ctx context.Context, input model.UpdateNoteInput) (*model.Note, error) {
	note, err := r.NotesClient.UpdateNote(ctx, input.ID, input.Title, input.Content)
	if err != nil {
		return nil, fmt.Errorf("failed to update note: %w", err)
	}

	// Convert to GraphQL note

	return &model.Note{
        ID:        note.Id,
        Title:     note.Title,
        Content:   note.Content,
        UserID:    note.UserId,
        CreatedAt: note.CreatedAt.AsTime(),
        UpdatedAt: note.UpdatedAt.AsTime(),
    }, nil
}

// DeleteNote is the resolver for the deleteNote field.
func (r *mutationResolver) DeleteNote(ctx context.Context, id string, userID string) (bool, error) {
	err := r.NotesClient.DeleteNote(ctx, id)
	if err != nil {
		return false, fmt.Errorf("failed to delete note: %w", err)
	}

	return true, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *noteResolver) CreatedAt(ctx context.Context, obj *model.Note) (string, error) {

	return obj.CreatedAt.String(), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *noteResolver) UpdatedAt(ctx context.Context, obj *model.Note) (string, error) {
	
	return obj.UpdatedAt.String(), nil
}

// Type is the resolver for the type field.
func (r *noteChangeResolver) Type(ctx context.Context, obj *model.NoteChange) (model.NoteChangeType, error) {
	switch obj.Type {
	case model.Created:
		return model.Created, nil
	case model.Updated:
		return model.Updated, nil
	case model.Deleted:
		return model.Deleted, nil
	default:
		return "", fmt.Errorf("unknown note change type: %v", obj.Type)
	}
}

// GetNote is the resolver for the getNote field.
func (r *queryResolver) GetNote(ctx context.Context, id string, userID string) (*model.Note, error) {
	note, err := r.NotesClient.GetNote(ctx, id, userID)
	if err != nil {
		return nil, err
	}

	return &model.Note{
        ID:        note.Id,
        Title:     note.Title,
        Content:   note.Content,
        UserID:    note.UserId,
        CreatedAt: note.CreatedAt.AsTime(),
        UpdatedAt: note.UpdatedAt.AsTime(),
    }, nil
}

// ListNotes is the resolver for the listNotes field.
func (r *queryResolver) ListNotes(ctx context.Context, userID string) ([]*model.Note, error) {
	note, err := r.NotesClient.ListNotes(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to list notes: %w", err)
	}

	var notes []*model.Note

	for _, n := range note {
		notes = append(notes, &model.Note{
			ID:        n.Id,
			Title:     n.Title,
			Content:   n.Content,
			UserID:    n.UserId,
			CreatedAt: n.CreatedAt.AsTime(),
			UpdatedAt: n.UpdatedAt.AsTime(),
		})
	}
	return notes, nil
}

// WatchNotes is the resolver for the watchNotes field.
func (r *subscriptionResolver) WatchNotes(ctx context.Context, userID string) (<-chan *model.NoteChange, error) {
	noteChangeChan := make(chan *model.NoteChange)
	
	// Create a channel for gRPC NoteChange events
	grpcChangeChan := make(chan *gen.NoteChange)
	
	// Start the gRPC subscription
	err := r.NotesClient.SubscribeToNoteChanges(ctx, userID, grpcChangeChan)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to note changes: %w", err)
	}
	
	// Start a goroutine to convert gRPC events to GraphQL events
	go func() {
		defer close(noteChangeChan)
		
		for {
			select {
			case grpcChange, ok := <-grpcChangeChan:
				if !ok {
					// Channel closed
					return
				}
				
				// Convert gRPC change type to GraphQL enum
				var changeType model.NoteChangeType
				switch grpcChange.Type {
				case gen.NoteChange_CREATED:
					changeType = model.Created
				case gen.NoteChange_UPDATED:
					changeType = model.Updated
				case gen.NoteChange_DELETED:
					changeType = model.Deleted
				default:
					// Skip unknown change types
					continue
				}
				
				// Convert the note
				note := &model.Note{
					ID:        grpcChange.Note.Id,
					Title:     grpcChange.Note.Title,
					Content:   grpcChange.Note.Content,
					UserID:    grpcChange.Note.UserId,
					CreatedAt: grpcChange.Note.CreatedAt.AsTime(),
					UpdatedAt: grpcChange.Note.UpdatedAt.AsTime(),
				}
				
				// Send the GraphQL NoteChange
				noteChangeChan <- &model.NoteChange{
					Type: changeType,
					Note: note,
				}
				
			case <-ctx.Done():
				// Context canceled
				return
			}
		}
	}()
	
	return noteChangeChan, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Note returns NoteResolver implementation.
func (r *Resolver) Note() NoteResolver { return &noteResolver{r} }

// NoteChange returns NoteChangeResolver implementation.
func (r *Resolver) NoteChange() NoteChangeResolver { return &noteChangeResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type noteResolver struct{ *Resolver }
type noteChangeResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
